---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-generator
  namespace: flink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-generator
  namespace: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink
subjects:
  - kind: ServiceAccount
    name: events-generator
    namespace: flink
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: events-generator
  namespace: flink
spec:
  flinkVersion: v2_0
  image: flink:2.0.1-scala_2.12-java17
  imagePullPolicy: IfNotPresent
  serviceAccount: events-generator
  job:
    jarURI: s3://flink/flink-autoscaler-0.12.jar
    entryClass: com.xebia.flink.workshop.autoscaler.EventsGenerator
    upgradeMode: savepoint
    state: running
    parallelism: 1
    args:
      - "--records-per-second"
      - "50.0"
  jobManager:
    replicas: 1
    resource:
      cpu: 0.5
      memory: 1024m
  taskManager:
    resource:
      cpu: 0.5
      memory: 1024m
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: events-generator-pod-template
    spec:
      containers:
        - name: flink-main-container
          ports:
            - containerPort: 9249
              name: metrics
          env:
            - name: ENABLE_BUILT_IN_PLUGINS
              value: "flink-s3-fs-presto-2.0.1.jar"
            - name: AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT
              value: "true"
  flinkConfiguration:
    rest.bind-port: "8082"
    execution.checkpointing.dir: "s3://flink/events-generator/checkpoints/"
    execution.checkpointing.interval: 60s
    execution.checkpointing.timeout: 1h
    execution.checkpointing.min-pause: 60s
    execution.checkpointing.savepoint-dir: "s3://flink/events-generator/savepoints/"
    high-availability.storageDir: "s3://flink/events-generator/high-availability/"
    high-availability.type: kubernetes
    kubernetes.rest-service.exposed.type: LoadBalancer
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    s3.access-key: admin
    s3.endpoint: http://minio.s3.svc.cluster.local:9000
    s3.path.style.access: "true"
    s3.secret-key: admin
    state.backend.type: hashmap
    taskmanager.numberOfTaskSlots: "1"
    web.cancel.enable: "true"
    web.submit.enable: "true"
    restart-strategy.type: exponential-delay
    restart-strategy.exponential-delay.initial-backoff: 60s
    restart-strategy.exponential-delay.max-backoff: 2h
    restart-strategy.exponential-delay.backoff-multiplier: "2"
    restart-strategy.exponential-delay.jitter-factor: "0.1"
    restart-strategy.exponential-delay.reset-backoff-threshold: 24h
    restart-strategy.exponential-delay.attempts-before-reset-backoff: "2147483647"