---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: events
  namespace: kafka
  labels:
    strimzi.io/cluster: rta-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: events2
  namespace: kafka
  labels:
    strimzi.io/cluster: rta-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000