---
webhook:
  create: false
watchNamespaces:
  - flink
operatorPod:
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 250m
      memory: 512Mi

metrics:
  port: 9999

defaultConfiguration:
  append: true
  flink-conf.yaml: |+
    kubernetes.operator.metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    kubernetes.operator.metrics.reporter.prom.port: 9999
