---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: left-join
  namespace: flink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: left-join
  namespace: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink
subjects:
  - kind: ServiceAccount
    name: left-join
    namespace: flink
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: left-join
  namespace: flink
spec:
  flinkVersion: v2_0
  image: flink:2.0.1-scala_2.12-java17
  imagePullPolicy: IfNotPresent
  serviceAccount: left-join
  job:
    jarURI: s3://flink//flink-workshop-0.9.jar
    entryClass: com.xebia.flink.LeftJoinJob
    upgradeMode: savepoint
    state: running
    parallelism: 1
  jobManager:
    replicas: 1
    resource:
      cpu: 0.4
      memory: 1024m
  taskManager:
    resource:
      cpu: 1.0
      memory: 1536m
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: left-join-pod-template
    spec:
      containers:
        - name: flink-main-container
          ports:
            - containerPort: 9249
              name: metrics
          env:
            - name: ENABLE_BUILT_IN_PLUGINS
              value: "flink-s3-fs-presto-2.0.1.jar"
            - name: AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT
              value: "true"
  flinkConfiguration:
    execution.checkpointing.dir: "s3://flink/left-join/checkpoints/"
    execution.checkpointing.interval: 60s
    execution.checkpointing.min-pause: 60s
    execution.checkpointing.savepoint-dir: "s3://flink/left-join/savepoints/"
    execution.checkpointing.timeout: 1h
    high-availability.storageDir: "s3://flink/left-join/high-availability/"
    high-availability.type: kubernetes
    kubernetes.rest-service.exposed.type: LoadBalancer
    metrics.reporter.prom.factory.class:
      org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    pipeline.max-parallelism: "4"
    rest.flamegraph.enabled: true
    restart-strategy.exponential-delay.attempts-before-reset-backoff: "2147483647"
    restart-strategy.exponential-delay.backoff-multiplier: "2"
    restart-strategy.exponential-delay.initial-backoff: 60s
    restart-strategy.exponential-delay.jitter-factor: "0.1"
    restart-strategy.exponential-delay.max-backoff: 2h
    restart-strategy.exponential-delay.reset-backoff-threshold: 24h
    restart-strategy.type: exponential-delay
    s3.access-key: admin
    s3.endpoint: http://minio.s3.svc.cluster.local:9000
    s3.path.style.access: true
    s3.secret-key: admin
    state.backend.incremental: "true"
    state.backend.rocksdb.metrics.block-cache-capacity: true
    state.backend.rocksdb.metrics.block-cache-hit: true
    state.backend.rocksdb.metrics.block-cache-miss: true
    state.backend.rocksdb.metrics.block-cache-pinned-usage: true
    state.backend.rocksdb.metrics.block-cache-usage: true
    state.backend.rocksdb.metrics.bloom-filter-full-positive: true
    state.backend.rocksdb.metrics.bloom-filter-full-true-positive: true
    state.backend.rocksdb.metrics.bloom-filter-useful: true
    state.backend.rocksdb.metrics.bytes-read: true
    state.backend.rocksdb.metrics.bytes-written: true
    state.backend.rocksdb.metrics.cur-size-active-mem-table: true
    state.backend.rocksdb.metrics.estimate-table-readers-mem: true
    state.backend.rocksdb.metrics.num-immutable-mem-table: true
    state.backend.rocksdb.metrics.size-all-mem-tables: true
    state.backend.rocksdb.predefined-options: FLASH_SSD_OPTIMIZED
    state.backend.rocksdb.use-bloom-filter: "true"
    state.backend.type: "rocksdb"
    taskmanager.numberOfTaskSlots: "1"
    web.cancel.enable: "true"
    web.submit.enable: "true"

